In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

print("at directory:", os.getcwd())
print("changing to root directory")
os.chdir("..")
print("at directory:", os.getcwd())

at directory: /Users/wilka/git/projects/multitask_preplay/figures_supplemental
changing to root directory
at directory: /Users/wilka/git/projects/multitask_preplay

In [3]:
sys.path.append("simulations")

In [4]:
from analysis import vis_utils
from data_processing import utils_jaxmaze as utils
from figures_supplemental.jaxmaze_overlap_analysis import visualize_examples_by_reuse
# visualize_model_overlap,
# compute_overlap_df,
# visualize_user_overlap,
# )

No file specified for image dict.
Using: /Users/wilka/git/projects/multitask_preplay/.venv/lib/python3.11/site-packages/jaxmaze/image_data.pkl
No file specified for groups.
Using: /Users/wilka/git/projects/multitask_preplay/.venv/lib/python3.11/site-packages/jaxmaze/human_dyna/list_of_groups.npy

# Model data

In [5]:
from data_processing import process_model_data

model_df = process_model_data.get_jaxmaze_model_data(
  load_df_only=True,
)

No file specified for groups.
Using: /Users/wilka/git/research/multitask_preplay/.venv/lib/python3.11/site-packages/jaxmaze/human_dyna/list_of_groups.npy
No file specified for groups.
Using: /Users/wilka/git/research/multitask_preplay/.venv/lib/python3.11/site-packages/jaxmaze/human_dyna/list_of_groups.npy
Generating model data for qlearning
Generating model data for dyna
Generating model data for usfa
Generating model data for preplay
Generating model data for bfs
Generating model data for dfs

In [6]:
model_df.filter(eval=True, manipulation="paths").head()

shape: (5, 22)
┌─────────┬───────────┬─────────┬─────────────┬───┬─────────────┬─────────────┬───────┬────────────┐
│ domain  ┆ algo      ┆ user_id ┆ manipulatio ┆ … ┆ task_vector ┆ task_object ┆ reuse ┆ train_test │
│ ---     ┆ ---       ┆ ---     ┆ n           ┆   ┆ ---         ┆ _id         ┆ ---   ┆ _cosine    │
│ str     ┆ str       ┆ i64     ┆ ---         ┆   ┆ str         ┆ ---         ┆ i32   ┆ ---        │
│         ┆           ┆         ┆ str         ┆   ┆             ┆ i64         ┆       ┆ f64        │
╞═════════╪═══════════╪═════════╪═════════════╪═══╪═════════════╪═════════════╪═══════╪════════════╡
│ jaxmaze ┆ qlearning ┆ 1       ┆ paths       ┆ … ┆ [0 0 1 0]   ┆ 47          ┆ 1     ┆ 0.999917   │
│ jaxmaze ┆ qlearning ┆ 1       ┆ paths       ┆ … ┆ [0 0 1 0]   ┆ 47          ┆ 1     ┆ 0.999917   │
│ jaxmaze ┆ qlearning ┆ 1       ┆ paths       ┆ … ┆ [0 0 1 0]   ┆ 47          ┆ 1     ┆ 0.706982   │
│ jaxmaze ┆ qlearning ┆ 1       ┆ paths       ┆ … ┆ [0 0 1 0]   ┆ 47          ┆ 1     ┆ 0.706982   │
│ jaxmaze ┆ qlearning ┆ 1       ┆ paths       ┆ … ┆ [0 0 1 0]   ┆ 47          ┆ 1     ┆ 0.554649   │
└─────────┴───────────┴─────────┴─────────────┴───┴─────────────┴─────────────┴───────┴────────────┘

In [7]:
manipulations = [
  {
    # "name": "shortcut",
    "manipulation": 1,
    "train_maze": "big_m1_maze3",
    "test_maze": "big_m1_maze3_shortcut",
  },
  {
    # "name": "two_paths",
    "manipulation": 3,
    "train_maze": "big_m3_maze1",
    "test_maze": "big_m3_maze1",
  },
]

threshold = 0.15
model = "preplay_new"
visualize_examples_by_reuse(
  df=model_df.filter(algo="preplay"),
  threshold=threshold,
  model=model,
  **manipulations[1],
)

TypeError: visualize_examples_by_reuse() got an unexpected keyword argument 'manipulation'

In [9]:
# Fix: manipulation column is a string ("paths", "shortcut"), not an int ID
manipulations = [
  {
    "manipulation_id": "shortcut",
    "train_maze": "big_m1_maze3",
    "test_maze": "big_m1_maze3_shortcut",
  },
  {
    "manipulation_id": "paths",
    "train_maze": "big_m3_maze1",
    "test_maze": "big_m3_maze1",
  },
]

threshold = 0.15
model = "preplay_new"
visualize_examples_by_reuse(
  df=model_df.filter(algo="preplay"),
  threshold=threshold,
  model=model,
  **manipulations[1],
)

Removing old data from /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new...
preplay_new - paths - threshold 0.15:
  Found 399 examples with overlap >= 0.15
  Found 0 examples with overlap < 0.15
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_01_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_02_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_03_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_04_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_05_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_06_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_07_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_08_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_09_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf
Saved figure to /Users/wilka/git/research/multitask_preplay/preplay_results/analysis_figures/jaxmaze_overlap_analysis/paths_0.15/preplay_new/above_threshold_example_10_reverse(Y=True,X=True)_overlap_0.684_reuse_1.pdf

# Human Overlap

In [5]:
from data_processing import process_user_data

user_df = process_user_data.get_jaxmaze_human_data(
  load_df_only=True,
)

No file specified for image dict.
Using: /Users/wilka/git/projects/multitask_preplay/.venv/lib/python3.11/site-packages/jaxmaze/image_data.pkl
GENERATING /Users/wilka/git/projects/raw_preplay_data/data/jaxmaze/final/human_data_episode_df.parquet
LOADING /Users/wilka/git/projects/raw_preplay_data/data/jaxmaze/final/human_data_episode_df.parquet

In [6]:
user_df.head()

shape: (5, 51)
┌─────────┬───────┬────────────┬─────────────┬───┬─────────────┬─────────────┬───────┬─────────────┐
│ domain  ┆ algo  ┆ user_id    ┆ manipulatio ┆ … ┆ train_succe ┆ min_train_s ┆ reuse ┆ approach_di │
│ ---     ┆ ---   ┆ ---        ┆ n           ┆   ┆ ss_count    ┆ uccess      ┆ ---   ┆ rection     │
│ str     ┆ str   ┆ i64        ┆ ---         ┆   ┆ ---         ┆ ---         ┆ i32   ┆ ---         │
│         ┆       ┆            ┆ str         ┆   ┆ f32         ┆ bool        ┆       ┆ str         │
╞═════════╪═══════╪════════════╪═════════════╪═══╪═════════════╪═════════════╪═══════╪═════════════╡
│ jaxmaze ┆ human ┆ 2551730852 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ -1    ┆ unknown     │
│ jaxmaze ┆ human ┆ 2551730852 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ -1    ┆ unknown     │
│ jaxmaze ┆ human ┆ 2551730852 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ -1    ┆ unknown     │
│ jaxmaze ┆ human ┆ 2551730852 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ -1    ┆ unknown     │
│ jaxmaze ┆ human ┆ 2551730852 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ -1    ┆ unknown     │
└─────────┴───────┴────────────┴─────────────┴───┴─────────────┴─────────────┴───────┴─────────────┘

In [7]:
len(user_df["global_episode_idx"].unique())

37617

In [8]:
# Fix: use string "shortcut" instead of int 1 for manipulation filter
shortcut_df = user_df.filter(manipulation="shortcut")
shortcut_df.filter(eval=True)

shape: (260, 51)
┌─────────┬───────┬────────────┬─────────────┬───┬─────────────┬─────────────┬───────┬─────────────┐
│ domain  ┆ algo  ┆ user_id    ┆ manipulatio ┆ … ┆ train_succe ┆ min_train_s ┆ reuse ┆ approach_di │
│ ---     ┆ ---   ┆ ---        ┆ n           ┆   ┆ ss_count    ┆ uccess      ┆ ---   ┆ rection     │
│ str     ┆ str   ┆ i64        ┆ ---         ┆   ┆ ---         ┆ ---         ┆ i32   ┆ ---         │
│         ┆       ┆            ┆ str         ┆   ┆ f32         ┆ bool        ┆       ┆ str         │
╞═════════╪═══════╪════════════╪═════════════╪═══╪═════════════╪═════════════╪═══════╪═════════════╡
│ jaxmaze ┆ human ┆ 2551730852 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 0     ┆ unknown     │
│ jaxmaze ┆ human ┆ 2551730852 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 1     ┆ unknown     │
│ jaxmaze ┆ human ┆ 2551730852 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 1     ┆ unknown     │
│ jaxmaze ┆ human ┆ 3761043368 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 1     ┆ unknown     │
│ jaxmaze ┆ human ┆ 3761043368 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 1     ┆ unknown     │
│ …       ┆ …     ┆ …          ┆ …           ┆ … ┆ …           ┆ …           ┆ …     ┆ …           │
│ jaxmaze ┆ human ┆ 3190803247 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 0     ┆ unknown     │
│ jaxmaze ┆ human ┆ 3190803247 ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 0     ┆ unknown     │
│ jaxmaze ┆ human ┆ 54971111   ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 1     ┆ unknown     │
│ jaxmaze ┆ human ┆ 54971111   ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 1     ┆ unknown     │
│ jaxmaze ┆ human ┆ 54971111   ┆ shortcut    ┆ … ┆ 16.0        ┆ true        ┆ 0     ┆ unknown     │
└─────────┴───────┴────────────┴─────────────┴───┴─────────────┴─────────────┴───────┴─────────────┘

In [9]:
# %debug
fig, train, test = visualize_user_overlap(shortcut_df, n=3)
fig

NameError: name 'visualize_user_overlap' is not defined

In [16]:
train

NameError: name 'train' is not defined

In [17]:
# visualize shortcut overlap
shortcut_df = user_df.filter(manipulation=1)
# visualize_user_overlap(shortcut_df, n=1)
print(len(user_df["user_id"].unique()))
user_id = shortcut_df["user_id"].unique().to_list()[2]
print(user_id)
test = shortcut_df.filter(eval=True, user_id=user_id, eval_shares_start_pos=True)
# test.head()
filters = dict(
  start_pos=test["start_pos"].to_list()[0],
  block_name=test["block_name"].to_list()[0],
  user_id=test["user_id"].to_list()[0],
  room=test["room"].to_list()[0],
)
# print(filters)
test = shortcut_df.filter(eval=True, manipulation=1, **filters)
train = shortcut_df.filter(eval=False, manipulation=1, success=1, **filters)

visualize_model_overlap(train, test, "shortcut/human", key="user_id")

ComputeError: cannot compare string with numeric type (i32)

In [18]:
# Fix: use string "shortcut" instead of int 1
shortcut_df = user_df.filter(manipulation="shortcut")
print(len(user_df["user_id"].unique()))
user_id = shortcut_df["user_id"].unique().to_list()[2]
print(user_id)
test = shortcut_df.filter(eval=True, user_id=user_id, eval_shares_start_pos=True)
filters = dict(
  start_pos=test["start_pos"].to_list()[0],
  block_name=test["block_name"].to_list()[0],
  user_id=test["user_id"].to_list()[0],
  room=test["room"].to_list()[0],
)
test = shortcut_df.filter(eval=True, manipulation="shortcut", **filters)
train = shortcut_df.filter(eval=False, manipulation="shortcut", success=1, **filters)

visualize_model_overlap(train, test, "shortcut/human", key="user_id")

593
77637731

ColumnNotFoundError: "room" not found

In [233]:
train

In [232]:
test

In [19]:
overlap = compute_overlap_df(train, test)
overlap.sum(), overlap.mean()

NameError: name 'compute_overlap_df' is not defined

In [20]:
vis_utils.render_path(test.episodes[0])

AttributeError: 'DataFrame' object has no attribute 'episodes'

In [21]:
vis_utils.render_path(train.episodes[0])
# vis_utils.render_path(train.episodes[1])
# vis_utils.render_path(train.episodes[2])

NameError: name 'train' is not defined

In [ ]:
# visualize two_paths overlap
train = user_df.filter(eval=False, manipulation=3, eval_shares_start_pos=True)
filters = dict(
  start_pos=test["start_pos"].to_list()[0],
  block_name=test["block_name"].to_list()[0],
  # user_id=test['user_id'].to_list()[0],
  room=test["room"].to_list()[0],
)
test = user_df.filter(eval=True, manipulation=3)

visualize_model_overlap(train, test, "two_paths/human", key="user_id")

In [ ]:
# Fix: use string "paths" instead of int 3
train = user_df.filter(eval=False, manipulation="paths", eval_shares_start_pos=True)
filters = dict(
  start_pos=test["start_pos"].to_list()[0],
  block_name=test["block_name"].to_list()[0],
  room=test["room"].to_list()[0],
)
test = user_df.filter(eval=True, manipulation="paths")

visualize_model_overlap(train, test, "two_paths/human", key="user_id")

# Model Overlap

In [138]:
from data_processing import process_model_data


model_df = process_model_data.get_jaxmaze_model_data(
  overwrite_episode_data=True,
  overwrite_episode_df=True,
  load_df_only=False,
  models=["preplay", "dyna", "usfa", "bfs"],
  debug=False,
)

No file specified for groups.
Using: /Users/wilka/git/research/human-dyna-web/libraries/housemaze/housemaze/human_dyna/list_of_groups.npy
No file specified for groups.
Using: /Users/wilka/git/research/human-dyna-web/libraries/housemaze/housemaze/human_dyna/list_of_groups.npy
No file specified for groups.
Using: /Users/wilka/git/research/human-dyna-web/libraries/housemaze/housemaze/human_dyna/list_of_groups.npy
No file specified for groups.
Using: /Users/wilka/git/research/human-dyna-web/libraries/housemaze/housemaze/human_dyna/list_of_groups.npy
No file specified for groups.
Using: /Users/wilka/git/research/human-dyna-web/libraries/housemaze/housemaze/human_dyna/list_of_groups.npy
No file specified for groups.
Using: /Users/wilka/git/research/human-dyna-web/libraries/housemaze/housemaze/human_dyna/list_of_groups.npy

KeyboardInterrupt:

In [133]:
model_df.filter(eval=True, manipulation=1, maze="big_m1_maze3_shortcut").head()
# model_df.filter(eval=False, manipulation=1, maze='big_m1_maze3')

In [ ]:
# Fix: use string "shortcut" instead of int 1
model_df.filter(eval=True, manipulation="shortcut", maze="big_m1_maze3_shortcut").head()

In [134]:
# for seed in range(1,11):
#     print(seed)
#     vis_utils.render_path(model_df.filter(eval=False, manipulation=1, maze='big_m1_maze3', seed=seed).episodes[0])

In [137]:
seed = None
train = model_df.filter(eval=False, manipulation=1, maze="big_m1_maze3", seed=seed)
test = model_df.filter(
  eval=True, manipulation=1, maze="big_m1_maze3_shortcut", seed=seed
)
visualize_model_overlap(train, test, f"shortcut_dfs", seeds=None)

/Users/wilka/git/research/human-dyna-web/libraries/nicewebrl/nicewebrl/dataframe.py:91: UserWarning: Comparisons with None always result in null. Consider using `.is_null()` or `.is_not_null()`.
  df = self._df.filter(*args, **kwargs)

Saved figure to /Users/wilka/git/research/preplay_results/figures/jaxmaze_model_overap/shortcut_dfs_model_overlap.pdf

In [ ]:
# Fix: use string "shortcut" instead of int 1
seed = None
train = model_df.filter(eval=False, manipulation="shortcut", maze="big_m1_maze3", seed=seed)
test = model_df.filter(
  eval=True, manipulation="shortcut", maze="big_m1_maze3_shortcut", seed=seed
)
visualize_model_overlap(train, test, f"shortcut_dfs", seeds=None)

In [121]:
train_map = utils.create_maps(train.filter(seed=seed).episodes[:1]).sum(0)
test_map = utils.create_maps(test.filter(seed=seed).episodes[:1]).sum(0)
overlap = utils.compute_overlap(train_map, test_map)
overlap.mean()

0.6

In [109]:
train.head()

In [110]:
train.episodes[0].timesteps.reward

Array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],      dtype=float32, weak_type=True)

In [111]:
from data_processing import process_model_data

in_episode = process_model_data.get_in_episode(train.episodes[0].timesteps)
rewards = train.episodes[0].timesteps.reward[in_episode]
rewards

Array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],      dtype=float32, weak_type=True)

In [112]:
success = rewards > 0.5
success

Array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False],      dtype=bool, weak_type=True)